# Generated by Django 4.0.4 on 2023-03-24 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_resusers_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resusers',
            table='res_users',
        ),
    ]
